In [83]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

data_train= pd.read_csv("train.csv")
data_test= pd.read_csv("test.csv")

In [84]:
data_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [85]:
data_train.shape,data_test.shape

((891, 12), (418, 11))

# Preprocessing

In [86]:
data_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [87]:
data_train = data_train.dropna(subset=["Embarked"])
data_test = data_test.dropna(subset=["Fare"])

# Name

In [88]:
train_test_data = [data_train, data_test]
for dataset in train_test_data:
    dataset['Title'] = dataset['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

<ipython-input-88-30c45d3d12ac>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Title'] = dataset['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
<ipython-input-88-30c45d3d12ac>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Title'] = dataset['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [89]:
data_train['Title'].value_counts()

Mr          517
Miss        181
Mrs         124
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Countess      1
Capt          1
Ms            1
Sir           1
Lady          1
Mme           1
Don           1
Jonkheer      1
Name: Title, dtype: int64

In [90]:
for dataset in train_test_data:
    # Replace some titles with more common titles
    dataset["Title"] = dataset["Title"].replace(['Mlle', 'Ms'], 'Miss')
    dataset["Title"] = dataset["Title"].replace('Mme', 'Mrs')
    # Replace values that are not in the ("Mr", "Miss", "Mrs", "Master") titles with "Rare", else keep the value
    dataset["Title"] = ["Rare" if value not in ["Mr", "Miss", "Mrs", "Master"] else value for value in dataset["Title"]]

# delete unnecessary feature from dataset
data_train.drop(['Ticket','Name'], axis=1, inplace=True)
data_test.drop(['Ticket','Name'], axis=1, inplace=True)

<ipython-input-90-bdd2e9ca1824>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Title"] = dataset["Title"].replace(['Mlle', 'Ms'], 'Miss')
<ipython-input-90-bdd2e9ca1824>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Title"] = dataset["Title"].replace('Mme', 'Mrs')
<ipython-input-90-bdd2e9ca1824>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Title"] = ["Rare" if value not in ["Mr", "Miss", "Mrs", "Master"] else value for value in dataset["Title"]]
<ipython-input-90-bdd2e9ca1824>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.drop(['Ticket','Name'], axis=1, inplace=True)
<ipython-input-90-bdd2e9ca1824>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test.drop(['Ticket','Name'], axis=1, inplace=True)

In [91]:
data_train.replace(["female","male"],[0,1],inplace=True)
data_train.replace(["C","S","Q"],[0,1,2],inplace=True)
data_train["Age"].fillna(data_train.groupby("Title")["Age"].transform("median"), inplace=True)
data_test.replace(["female","male"],[0,1],inplace=True)
data_test.replace(["C","S","Q"],[0,1,2],inplace=True)
data_test["Age"].fillna(data_test.groupby("Title")["Age"].transform("median"), inplace=True)

<ipython-input-91-813d7da7e537>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.replace(["female","male"],[0,1],inplace=True)
<ipython-input-91-813d7da7e537>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.replace(["C","S","Q"],[0,1,2],inplace=True)
<ipython-input-91-813d7da7e537>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train["Age"].fillna(data_train.groupby("Title")["Age"].transform("median"), inplace=True)
<ipython-input-91-813d7da7e537>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test.replace(["female","male"],[0,1],inplace=True)
<ipython-input-91-813d7da7e537>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test.replace(["C","S","Q"],[0,1,2],inplace=True)
<ipython-input-91-813d7da7e537>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test["Age"].fillna(data_test.groupby("Title")["Age"].transform("median"), inplace=True)

In [92]:
data_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Fare             0
Cabin          687
Embarked         0
Title            0
dtype: int64

In [93]:
for dataset in train_test_data:
    dataset['Cabin'] = dataset['Cabin'].str[:1]

cabin_mapping = {"A": 0, "B": 0.4, "C": 0.8, "D": 1.2, "E": 1.6, "F": 2, "G": 2.4, "T": 2.8}
for dataset in train_test_data:
    dataset['Cabin'] = dataset['Cabin'].map(cabin_mapping)

<ipython-input-93-a5cad012cf75>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Cabin'] = dataset['Cabin'].str[:1]
<ipython-input-93-a5cad012cf75>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Cabin'] = dataset['Cabin'].map(cabin_mapping)
<ipython-input-93-a5cad012cf75>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Cabin'] = dataset['Cabin'].map(cabin_mapping)

In [94]:
data_train["Cabin"].fillna(data_train.groupby("Pclass")["Cabin"].transform("median"), inplace=True)
data_test["Cabin"].fillna(data_test.groupby("Pclass")["Cabin"].transform("median"), inplace=True)

<ipython-input-94-e968bdd61b30>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train["Cabin"].fillna(data_train.groupby("Pclass")["Cabin"].transform("median"), inplace=True)
<ipython-input-94-e968bdd61b30>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test["Cabin"].fillna(data_test.groupby("Pclass")["Cabin"].transform("median"), inplace=True)

In [95]:
data_train['Title'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Rare'], dtype=object)

In [96]:
data_train.replace(['Mr', 'Mrs', 'Miss', 'Master', 'Rare'],[0,1,2,3,4],inplace=True)
data_test.replace(['Mr', 'Mrs', 'Miss', 'Master', 'Rare'],[0,1,2,3,4],inplace=True)

<ipython-input-96-bd37c07b3e74>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.replace(['Mr', 'Mrs', 'Miss', 'Master', 'Rare'],[0,1,2,3,4],inplace=True)
<ipython-input-96-bd37c07b3e74>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_test.replace(['Mr', 'Mrs', 'Miss', 'Master', 'Rare'],[0,1,2,3,4],inplace=True)

In [97]:
data_train.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Title
0,1,0,3,1,22.0,1,0,7.2500,2.0,1,0
1,2,1,1,0,38.0,1,0,71.2833,0.8,0,1
2,3,1,3,0,26.0,0,0,7.9250,2.0,1,2
3,4,1,1,0,35.0,1,0,53.1000,0.8,1,1
4,5,0,3,1,35.0,0,0,8.0500,2.0,1,0
5,6,0,3,1,30.0,0,0,8.4583,2.0,2,0
6,7,0,1,1,54.0,0,0,51.8625,1.6,1,0
7,8,0,3,1,2.0,3,1,21.0750,2.0,1,3
8,9,1,3,0,27.0,0,2,11.1333,2.0,1,1
9,10,1,2,0,14.0,1,0,30.0708,1.8,0,1

In [98]:
data_train.corr()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Title
PassengerId,1.000000,-0.005028,-0.035330,0.043136,0.040311,-0.057686,-0.001657,0.012703,-0.037735,-0.017487,-0.023664
Survived,-0.005028,1.000000,-0.335549,-0.541585,-0.083817,-0.034040,0.083151,0.255290,-0.274985,-0.126753,0.405078
Pclass,-0.035330,-0.335549,1.000000,0.127741,-0.350958,0.081656,0.016824,-0.548193,0.864176,0.307324,-0.118595
Sex,0.043136,-0.541585,0.127741,1.000000,0.110289,-0.116348,-0.247508,-0.179958,0.086865,0.023175,-0.564014
Age,0.040311,-0.083817,-0.350958,0.110289,1.000000,-0.264994,-0.187232,0.095027,-0.309581,-0.066795,-0.282136
SibSp,-0.057686,-0.034040,0.081656,-0.116348,-0.264994,1.000000,0.414542,0.160887,0.070307,0.031095,0.270439
Parch,-0.001657,0.083151,0.016824,-0.247508,-0.187232,0.414542,1.000000,0.217532,0.013944,-0.035756,0.268780
Fare,0.012703,0.255290,-0.548193,-0.179958,0.095027,0.160887,0.217532,1.000000,-0.575547,-0.269588,0.139572
Cabin,-0.037735,-0.274985,0.864176,0.086865,-0.309581,0.070307,0.013944,-0.575547,1.000000,0.323641,-0.116459
Embarked,-0.017487,-0.126753,0.307324,0.023175,-0.066795,0.031095,-0.035756,-0.269588,0.323641,1.000000,0.020633
Title,-0.023664,0.405078,-0.118595,-0.564014,-0.282136,0.270439,0.268780,0.139572,-0.116459,0.020633,1.000000

# Model

In [146]:
X=data_train[['Pclass','Sex','Fare','Cabin','Embarked','Title']]
Y=data_train[['Survived']]


X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
print((Y_test.iloc[0][0]))

0

In [176]:
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, Y_train)).shuffle(10).batch(6)
test_dataset = tf.data.Dataset.from_tensor_slices((X_test, Y_test)).batch(6)

In [116]:
# X_train = tf.convert_to_tensor(X_train)
# Y_train = tf.convert_to_tensor(Y_train)
# X_test = tf.convert_to_tensor(X_test)
# Y_test = tf.convert_to_tensor(Y_test)
# print(X_train[0])
# X_train[0].shape

In [177]:
Y_train.shape
X_train.shape

(711, 6)

In [103]:
# X_train = X_train[..., tf.newaxis]
# X_test = X_test[..., tf.newaxis]
# X_train[0].shape

In [178]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D

class MyModel(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.d1 = Dense(6, activation="relu")
    # self.d2 = Dense(36, activation="relu")
    self.d3 = Dense(18, activation="relu")
    self.d4 = Dense(2, activation="softmax")

  def call(self, x):
    x = self.d1(x)
    # x = self.d2(x)
    x = self.d3(x)
    x = self.d4(x)
    return x

model = MyModel()

In [179]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy()#from_logits=True)
optimizer = tf.keras.optimizers.Adamax(learning_rate=0.01)

In [180]:
train_loss = tf.keras.metrics.Mean()
test_loss = tf.keras.metrics.Mean()

train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

In [181]:
@tf.function
def train(xtrain, label):
    with tf.GradientTape() as tape:
      pred = model(xtrain)
      # print(pred, pred.shape)
      # print(label, label.shape)
      loss = loss_function(label, pred)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_accuracy(label, pred)

@tf.function
def test(xtest, label):
    pred = model(xtest)
    loss = loss_function(label, pred)
    test_loss(loss)
    test_accuracy(label, pred)

In [ ]:
epochs = 50
best_accuracy = 0
for epoch in range(epochs):
  # train_loss.reset_states()
  # train_accuracy.reset_states()
  # test_loss.reset_states()
  # test_accuracy.reset_states()
  #train
  for xtrain, label in train_dataset:
    train(xtrain, label)

    #test
  for xtest, label in test_dataset:
    test(xtest, label)
  test_best_accuracy = test_accuracy.result()
  if test_best_accuracy > best_accuracy:
    model.save("titanic_best_model")
    best_accuracy = test_best_accuracy
  print("epoch:", epoch+1,
        f"Train Loss: {train_loss.result()}",
        f"Train accuracy: {train_accuracy.result()}",
        f"Test Loss: {test_loss.result()}",
        f"Test accuracy, {test_best_accuracy}")

epoch: 1 Train Loss: 0.5053476691246033 Train accuracy: 0.7623341679573059 Test Loss: 0.49981531500816345 Test accuracy, 0.7664217948913574
epoch: 2 Train Loss: 0.5048543810844421 Train accuracy: 0.7626041173934937 Test Loss: 0.49968039989471436 Test accuracy, 0.7665889263153076
epoch: 3 Train Loss: 0.5045675039291382 Train accuracy: 0.7627577185630798 Test Loss: 0.49955931305885315 Test accuracy, 0.766749918460846
epoch: 4 Train Loss: 0.5040585994720459 Train accuracy: 0.7630879878997803 Test Loss: 0.49941951036453247 Test accuracy, 0.7669050097465515
epoch: 5 Train Loss: 0.5032830238342285 Train accuracy: 0.7633550763130188 Test Loss: 0.49931058287620544 Test accuracy, 0.767054557800293
epoch: 6 Train Loss: 0.5029044151306152 Train accuracy: 0.7635372877120972 Test Loss: 0.49931955337524414 Test accuracy, 0.767001748085022
epoch: 7 Train Loss: 0.5020375847816467 Train accuracy: 0.7638117671012878 Test Loss: 0.49922648072242737 Test accuracy, 0.767144501209259
epoch: 8 Train Loss: 0.501916766166687 Train accuracy: 0.7641010880470276 Test Loss: 0.4991177022457123 Test accuracy, 0.7672824263572693
epoch: 9 Train Loss: 0.501450777053833 Train accuracy: 0.7642852067947388 Test Loss: 0.49902817606925964 Test accuracy, 0.7673221230506897
epoch: 10 Train Loss: 0.5011746883392334 Train accuracy: 0.7645569443702698 Test Loss: 0.49889203906059265 Test accuracy, 0.767452597618103
epoch: 11 Train Loss: 0.5008348226547241 Train accuracy: 0.7647275924682617 Test Loss: 0.49872031807899475 Test accuracy, 0.7675788402557373
epoch: 12 Train Loss: 0.5005295872688293 Train accuracy: 0.764960765838623 Test Loss: 0.49854356050491333 Test accuracy, 0.7677010893821716
epoch: 13 Train Loss: 0.5000922679901123 Train accuracy: 0.7651419043540955 Test Loss: 0.49839791655540466 Test accuracy, 0.7678195238113403
epoch: 14 Train Loss: 0.499789834022522 Train accuracy: 0.765383243560791 Test Loss: 0.4982838034629822 Test accuracy, 0.7679343223571777
epoch: 15 Train Loss: 0.49919143319129944 Train accuracy: 0.7656821608543396 Test Loss: 0.49812883138656616 Test accuracy, 0.7679604887962341
epoch: 16 Train Loss: 0.49868249893188477 Train accuracy: 0.7659293413162231 Test Loss: 0.49793457984924316 Test accuracy, 0.7680697441101074
epoch: 17 Train Loss: 0.4982238709926605 Train accuracy: 0.7661901712417603 Test Loss: 0.4977272152900696 Test accuracy, 0.7681757807731628
epoch: 18 Train Loss: 0.4977687895298004 Train accuracy: 0.766339898109436 Test Loss: 0.4974973201751709 Test accuracy, 0.7681973576545715
epoch: 19 Train Loss: 0.4973916709423065 Train accuracy: 0.7666482925415039 Test Loss: 0.49728894233703613 Test accuracy, 0.7682985663414001
epoch: 20 Train Loss: 0.4969842731952667 Train accuracy: 0.7668675780296326 Test Loss: 0.4970667064189911 Test accuracy, 0.7683969140052795
epoch: 21 Train Loss: 0.49659964442253113 Train accuracy: 0.7671005129814148 Test Loss: 0.4968346357345581 Test accuracy, 0.7684144973754883
epoch: 22 Train Loss: 0.49616020917892456 Train accuracy: 0.7672292590141296 Test Loss: 0.4966007471084595 Test accuracy, 0.7684316039085388
epoch: 23 Train Loss: 0.4957500398159027 Train accuracy: 0.7674700617790222 Test Loss: 0.49637076258659363 Test accuracy, 0.7684482336044312
epoch: 24 Train Loss: 0.4953133761882782 Train accuracy: 0.7677804231643677 Test Loss: 0.4961853325366974 Test accuracy, 0.7686142325401306
epoch: 25 Train Loss: 0.49490416049957275 Train accuracy: 0.7679887413978577 Test Loss: 0.4959668219089508 Test accuracy, 0.7686280012130737
epoch: 26 Train Loss: 0.4946127235889435 Train accuracy: 0.7681545615196228 Test Loss: 0.49577128887176514 Test accuracy, 0.7687873840332031
epoch: 27 Train Loss: 0.49420589208602905 Train accuracy: 0.7683526277542114 Test Loss: 0.49554720520973206 Test accuracy, 0.7688706517219543
epoch: 28 Train Loss: 0.4939239025115967 Train accuracy: 0.7685816287994385 Test Loss: 0.4953031837940216 Test accuracy, 0.7688806653022766
epoch: 29 Train Loss: 0.49366527795791626 Train accuracy: 0.7687870264053345 Test Loss: 0.49508005380630493 Test accuracy, 0.7688904404640198
epoch: 30 Train Loss: 0.49337077140808105 Train accuracy: 0.7689873576164246 Test Loss: 0.4949003756046295 Test accuracy, 0.7689693570137024
epoch: 31 Train Loss: 0.49294254183769226 Train accuracy: 0.7692347764968872 Test Loss: 0.49468448758125305 Test accuracy, 0.7689778208732605
epoch: 32 Train Loss: 0.4925515353679657 Train accuracy: 0.7693904042243958 Test Loss: 0.4944959580898285 Test accuracy, 0.7691214084625244
epoch: 33 Train Loss: 0.4921897351741791 Train accuracy: 0.7695253491401672 Test Loss: 0.4942934215068817 Test accuracy, 0.7691279053688049
epoch: 34 Train Loss: 0.49184972047805786 Train accuracy: 0.7697575688362122 Test Loss: 0.4941384196281433 Test accuracy, 0.7692663669586182
epoch: 35 Train Loss: 0.49138641357421875 Train accuracy: 0.7699015736579895 Test Loss: 0.49395424127578735 Test accuracy, 0.7692709565162659
epoch: 36 Train Loss: 0.49096551537513733 Train accuracy: 0.7700585722923279 Test Loss: 0.49375566840171814 Test accuracy, 0.7692754864692688
epoch: 37 Train Loss: 0.4905940294265747 Train accuracy: 0.770244300365448 Test Loss: 0.4935491383075714 Test accuracy, 0.7693437337875366
epoch: 38 Train Loss: 0.490090012550354 Train accuracy: 0.7703778147697449 Test Loss: 0.49338269233703613 Test accuracy, 0.7693473100662231

In [ ]:
type(X_test)
X_test.iloc[0]

In [191]:

pred = model(tf.convert_to_tensor(X_test.iloc[0:6]))
for i,p in enumerate(pred):
  print("predict:",np.argmax(p),"real:",Y_test.iloc[i][0])

predict: 1 real: 0
predict: 0 real: 0
predict: 1 real: 1
predict: 0 real: 0
predict: 0 real: 0
predict: 0 real: 0

In [188]:
best_model =  tf.keras.models.load_model("titanic_best_model")
for xtest, label in test_dataset:
    pred = best_model(xtest)
    loss = loss_function(label, pred)
    test_loss(loss)
    test_accuracy(label, pred)
print(
      f"Test Loss: {test_loss.result()}",
      f"Test accuracy, {test_accuracy.result()}")

WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.

Test Loss: 0.4912276268005371 Test accuracy, 0.7714254260063171